### ISSUE TITLE
Pinch of Intelligence Link return 521 error

### ISSUE THREAD

**Issue by hkiang01** [markjay4k/Fashion-MNIST-with-Keras#2]

**Comment by markjay4k** [comment]
yes, I checked as well and saw that it is gone. hopefully the video is enough to follow along

**Comment by hkiang01** [comment]
I think I found the missing link: http://www.pinchofintelligence.com/simple-introduction-to-tensorboard-embedding-visualisation/

**Comment by hkiang01** [comment]
https://github.com/markjay4k/Fashion-MNIST-with-Keras/pull/3

**Comment by markjay4k** [comment]
thank you!
